config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get    '/top',      to: 'static_pages#top'
  get    'staff',     to: 'static_pages#staff'
  get 'new_review',   to: 'static_pages#new_review'
  get    '/signup',   to: 'users#new'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  post '/gest_login', to: 'gest_login#new_gest'
  post 'admin_login', to: 'gest_login#new_admin_gest'
  resources :users
  resources :reservations, only: [:index, :new, :create, :destroy]
  resources :menus, only: [:index, :new, :show, :create, :destroy] do
    resources :reviews, only: [:index, :create, :destroy]
  end
  resources :requests,    only: [:index, :show, :new, :create, :destroy] do
    resources :comments,  only: [:create, :destroy]
    post '/add', to: 'favorites#create'
    delete '/add', to: 'favorites#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user, only: [:top]
  def home
  end

  def top
  end

  def staff
  end

  def new_review
    @menus = Menu.all
  end
end

app/views/static_pages/_sub_content.html.erb
<div class="sub_content">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h2>オフィスパとは？</h2>
        <h3>〜オフィスで受けれるマッサージサービス〜</h3>
        <h4>デスクワークでの首肩コリ、眼精疲労を撃退</h4>
        <p>必要な物はいっさいなし<br>あなたは椅子に座って待っているだけ。</p>
      </div>
      <div class="col-md-6">
        <%= image_tag 'spa.jpg' %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_top.html.erb
<div class="top_page">
  <div class="top_image">
    <div class="top_comment">
      <h1>生産性をあげよう</h1>
      <h2>頭痛は脳のSOS</h2>
    </div>
  </div>
  <div id="flex_link">
    <% if current_user.admin? %>
      <div class="flex-item"><%= link_to "予約確認", reservations_path, class: "btn btn-success" %></div>
      <div class="flex-item"><%= link_to "メニュー投稿", new_menu_path, class: "btn btn-success" %></div>
      <div class="flex-item"><%= link_to "口コミ確認", new_review_path, class: "btn btn-success" %></div>
      <div class="flex-item"><%= link_to "要望確認", requests_path, class: "btn btn-success" %></div>
      <div class="flex-item"><%= link_to "ユーザー一覧", users_path, class: "btn btn-success user_link" %></div>
    <% else %>
      <div class="flex-item"><%= link_to "予約する", new_reservation_path, class: "btn btn-success" %></div>
      <div class="flex-item"><%= link_to "メニュー", menus_path, class: "btn btn-success" %></div>
      <div class="flex-item"><%= link_to "スタッフ", staff_path, class: "btn btn-success" %></div>
      <div class="flex-item"><%= link_to "口コミ", new_review_path, class: "btn btn-success" %></div>
      <div class="flex-item"><%= link_to "要望", new_request_path, class: "btn btn-success" %></div>
      <div class="flex-item"><%= link_to "マイページ", current_user, class: "btn btn-success user_link" %></div>
    <% end %>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <%= render "top" %>
<% else %>
  <div class="main">
    <%= render "layouts/header" %>
    <div class="cf"></div>
    <div class="description">
      <h1>仕事の合間にヘッドスパ</h1>
      <p>
      ベンチャースタートアップ企業向け<br>福利厚生サービス、オフィスでスパ！
      </p>
    </div>
    <div class="cf">
    <div class="gest">
      <%= link_to "ゲストログイン(ユーザー)", gest_login_path, method: :post, class: "btn btn-primary gest_login" %>
      <%= link_to "ゲストログイン(管理者用)", admin_login_path, method: :post, class: "btn btn-primary admin_login" %>
    </div>
  </div>
  <div class="cf"></div>
  <%= render 'static_pages/sub_content' %>
  <footer class="home">
    <p>Copyright オフィスパ All Rights Reserved</p>
  </footer>
<% end %>

app/views/static_pages/new_review.html.erb
<%= provide(:title, "口コミ") %>
<div class="new_review_page">
  <div class="backcolor">
    <% unless current_user.admin? %>
      <h2>口コミを投稿しよう！</h2>
    <% else %>
      <h2>口コミを確認</h2>
    <% end %>
    <div class="container">
      <% @menus.each do |menu| %>
        <div class="review_page_box">
          <h3><%= menu.name %></h3>
          <p>
            <%= image_tag menu.display_image if menu.image.attached? %>
          </p>
          <div class="review_light">
            <% unless current_user.admin? %>
              <span><%= link_to "口コミを書く", menu_path(menu.id), class: "btn btn-primary review_id_link" %></span>
            <% end %>
            <span><%= link_to "口コミを見る", menu_reviews_path(menu.id), class: "btn btn-primary review_see" %></span>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/staff.html.erb
<%= provide(:title, "スタッフ") %>
<div class="staff_page">
  <div class="contents">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <%= image_tag 'staff.jpg' %>
        </div>
        <div class="col-md-6">
          <div class="staff_description">
            <h3>阿部航平</h3>
            <span>Kohei abe</span>
          </div>
          <div class="sub_description">
            <span>〜経歴〜</span>
            <p class="lead">芸能人やモデルも多数通う有名隠れ家サロンでヘッドスパ、ボディ、
              フェイシャルをメインに３年間勤務。企業向けに出張ヘッドスパ経験も多数。
            </p>
            <span>〜企業向け実績〜</span>
            <p class="lead">ヤフー株式会社、アクサ・ホールディングス・ジャパン株式会社、
              WeWork Companies、レクサス青山
            </p>
            <span>〜スキル〜</span>
            <p class="lead">HTML, CSS, Ruby,Ruby on Rails, JavaScript, SQL, Rspec,
              Docker, Git, github, circleCi, AWS, heroku
            </p>
          </div>
          <div class="cf"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/top.html.erb
<%= render "top" %>