config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get    '/top',      to: 'static_pages#top'
  get    'staff',     to: 'static_pages#staff'
  get 'new_review',   to: 'static_pages#new_review'
  get    '/signup',   to: 'users#new'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  post '/gest_login', to: 'gest_login#new_gest'
  post 'admin_login', to: 'gest_login#new_admin_gest'
  resources :users
  resources :reservations, only: [:index, :new, :create, :destroy]
  resources :menus, only: [:index, :new, :show, :create, :destroy] do
    resources :reviews, only: [:index, :create, :destroy]
  end
  resources :requests,    only: [:index, :show, :new, :create, :destroy] do
    resources :comments,  only: [:create, :destroy]
    post '/add', to: 'favorites#create'
    delete '/add', to: 'favorites#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :requests, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reviews,  dependent: :destroy
  has_many :favorites
  has_many :reservations, dependent: :destroy
  # 管理者が誤って削除された場合メニューが全て削除されては困るのでdependentはつけない
  has_many :menus
  has_many :request_favorite, through: :favorites
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 200 },
                    format: { with: Const::VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :description, length: { maximum: 140 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :destroy, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy, :index]
  before_action :set_user,       only: [:show, :edit]
  def new
    @user = User.new
  end

  def show
    @reservations = @user.reservations.reservations_history(10)
    @menus = Menu.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to top_path
      flash[:success] = "さっそく予約してみよう！"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "ユーザーを編集しました"
      redirect_to @user
    else
      render 'edit'
      flash.now[:danger] = "編集に失敗しました"
    end
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless @user == current_user
  end
end

app/views/users/_reservations_history.html.erb
<% if current_user %>
  <div class="visit_history">
    <table>
      <thead>
        <tr>
          <th>予約名</th>
          <th>予約時間</th>
          <th>メニュー</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @reservations.each do |reservation| %>
          <tr>
            <td><%= reservation.name %></td>
            <td><%= reservation.start_time %></td>
            <th><%=link_to reservation.menu.name, menus_path, class: "history_menu" unless reservation.menu.nil? %></th>
            <!-- メニューテーブルと予約テーブルを後から関連付けしたため過去の予約のメニューがnil classになるのを防ぐため条件分岐 -->
            <td><%= link_to 'キャンセル', reservation, method: :delete, data: { confirm: '本当にキャンセルしますか？' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= image_tag "user.jpg" %>
  <%= link_to user.name, user, class: "user_name" %>
  <% if current_user.admin? %>
    | <%= link_to "削除する", user, method: :delete, data: { confirm: "本当に削除しますか?" }, class: "delete" %>
  <% end %>
</li>

app/views/users/edit.html.erb
<%= provide(:title, "編集") %>
<div class="user_edit">
  <div class="container">
    <h1>編集</h1>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_with(model: @user, local: true) do |f| %>
          <%= render "shared/error_messages", object: f.object %>

          <%= f.label :name, "名前" %>
          <%= f.text_field :name, class: 'form-control' %>

          <%= f.label :email, "メールアドレス" %>
          <%= f.email_field :email, class: 'form-control' %>

          <%= f.label :password, "パスワード(６文字以上)" %>
          <%= f.password_field :password, class: 'form-control' %>

          <%= f.label :password_confirmation, "パスワード(確認用)" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>

          <%= f.submit "編集する", class: "btn btn-primary edit_btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= provide(:title, "ユーザー一覧") %>
<div class="container">
  <%= will_paginate %>

  <div class="user_index">
    <ul class="users">
      <%= render @users %>
    </ul>
  </div>
  <div class="cd"></div>

  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, '新規作成') %>
<%= render "layouts/header" %>
<div class="signup">
  <div class="signup_link">
    <h1>新規登録</h1>
    <div class="container">
      <div class="row-sm-12">
        <div class="col-sm-12">
          <%= form_with(model: @user, local: true) do |f| %>
            <%= render "shared/error_messages", object: f.object %>
            
            <%= f.label :name, "フルネーム" %>
            <%= f.text_field :name %>

            <%= f.label :email, "メールアドレス" %>
            <%= f.email_field :email %>

            <%= f.label :password, "パスワード(6文字以上)" %>
            <%= f.password_field :password %>

            <%= f.label :password_confirmation, "パスワード(確認用)" %>
            <%= f.password_field :password_confirmation %>

            <%= f.submit "作成する", class: "btn btn-primary signup_btn" %>
          <% end %>
          <%= link_to "ゲストとしてログインする", gest_login_path, method: :post, class: "gest" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="user_page">
  <div class="user_image">
    <%= image_tag "user.jpg" %> 
  </div>
  <div class="user_name">
    <%= @user.name %> 
  </div>
  <% if current_user.id == @user.id %>
    <%= link_to "編集する", edit_user_path(current_user), class: "btn btn-primary btn-lg edit_btn" %>
  <% end %>
  <%= link_to "ユーザーを削除", @user, method: :delete, data: { confirm: "本当に削除しますか?" },
    class: "btn btn-danger btn-lg user_destroy" if current_user.admin? %>
</div>
<%= render "reservations_history", reservaions: @reservations, menus: @menus %>