config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get    '/top',      to: 'static_pages#top'
  get    'staff',     to: 'static_pages#staff'
  get 'new_review',   to: 'static_pages#new_review'
  get    '/signup',   to: 'users#new'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  post '/gest_login', to: 'gest_login#new_gest'
  post 'admin_login', to: 'gest_login#new_admin_gest'
  resources :users
  resources :reservations, only: [:index, :new, :create, :destroy]
  resources :menus, only: [:index, :new, :show, :create, :destroy] do
    resources :reviews, only: [:index, :create, :destroy]
  end
  resources :requests,    only: [:index, :show, :new, :create, :destroy] do
    resources :comments,  only: [:create, :destroy]
    post '/add', to: 'favorites#create'
    delete '/add', to: 'favorites#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  def index
    @menu = Menu.find(params[:menu_id])
    @reviews = @menu.reviews
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to menu_reviews_path(@review.menu)
      flash[:success] = "口コミを投稿しました"
    else
      @menu = Menu.find(params[:menu_id])
      render "menus/show"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:success] = "口コミを削除しました"
    redirect_to menus_path
  end

  private

  def review_params
    params.require(:review).permit(:menu_id, :score, :content)
  end
end

app/views/reviews/_review.html.erb
<div class="review_user_box">
  <div class="user_name_box">
    <%= image_tag "user.jpg" %>
    <span class="review_user_name"><%= review.user.name %> さんの口コミ</span>
  </div>
  <div class="user_score">
    <p>評価  <%= review.score %></p>
    <span><%= time_ago_in_words(review.created_at)+"前" %></span>
  </div>
  <div class="review_description_box">
    <p class="review_description">
      <%= review.content %>
    </p>
    <% if current_user == review.user %>
      <%= link_to "口コミを削除する", menu_review_path(review, review.id),
          method: :delete, class: "review_delet_btn", method: :delete, data: {confirm: "本当に削除しますか？"} %>
    <% end %>
  </div>
</div>

app/views/reviews/_review_form.html.erb
<div class="rating-box">
  <%= form_with model: review, url: menu_reviews_path(menu), local: true do |f| %>
    <div class="main-rating">
      <div class="ratings">
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
      </div>
      <div class="rating-value-display"><span id="rating-value-display">0</span>/5</div>
    </div>
    <%= render "shared/error_messages", object: f.object %>
    <%= f.hidden_field :menu_id, value: menu.id %>
    <%= f.hidden_field :score, id: "rating-value" %>
    <%= f.text_area :content, class: "textarea review_content" %>
    <%= f.submit "口コミを投稿する", class: "btn btn-primary" %>
    <P>
      <%= link_to "口コミを確認する", menu_reviews_path(menu), class: "other_btn" %>
    </P>
  <% end %>
</div>
<%= javascript_pack_tag 'reviews.js' %>

app/views/reviews/index.html.erb
<%= provide(:title, "口コミ一覧") %>
<div class="menu_review_index">
  <div class="container">
    <div class="menu_description_box">
      <h2 class="menu_title"><%= @menu.name %></h2>
       <div class="content average-score">
        <div class="star-rating">
          <div class="star-rating-front" style="width: <%= @menu.review_score_percentage %>%">★★★★★</div>
          <div class="star-rating-back">★★★★★</div>
        </div>
      </div>
      <div class="average-score-display">
        平均<%= @menu.avg_score %>点（<%= @menu.reviews.count %>件の口コミ）
      </div>
      <%= link_to "口コミを投稿する", menu_path(@menu.id) %>
    </div>
    <%= render @reviews %>
  </div>
</div>