config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get    '/top',      to: 'static_pages#top'
  get    'staff',     to: 'static_pages#staff'
  get 'new_review',   to: 'static_pages#new_review'
  get    '/signup',   to: 'users#new'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  post '/gest_login', to: 'gest_login#new_gest'
  post 'admin_login', to: 'gest_login#new_admin_gest'
  resources :users
  resources :reservations, only: [:index, :new, :create, :destroy]
  resources :menus, only: [:index, :new, :show, :create, :destroy] do
    resources :reviews, only: [:index, :create, :destroy]
  end
  resources :requests,    only: [:index, :show, :new, :create, :destroy] do
    resources :comments,  only: [:create, :destroy]
    post '/add', to: 'favorites#create'
    delete '/add', to: 'favorites#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin_footer.html.erb
<li class="flex_item">
  <%= link_to new_reservation_path do %>
    <%= icon("fas", "clock", class: "clock-icon") %>
    <h4>予約</h4>
  <% end %>
</li>
<li class="flex_item">
  <%= link_to current_user do %>
    <%= icon("fas", "user", class: "user-icon") %>
    <h4 class="user-footer-link">マイページ</h4>
  <% end %>
</li>

app/views/layouts/_footer.html.erb
<div class="heading">
  <p>Copyright オフィスパ All Rights Reserved</p>
</div>
<footer>
  <ul class="flex-list">
    <li class="flex_item">
      <%= link_to top_path do %>
        <%= icon("fas", "home", class: "home-icon") %>
        <h4>ホーム</h4>
      <% end %>
    </li>
    <% if current_user.admin? %>
      <li class="flex_item">
        <%= link_to reservations_path do %>
          <%= icon("fas", "clock", class: "clock-icon") %>
          <h4>予約一覧</h4>
        <% end %>
      </li>
      <li class="flex_item">
        <%= link_to users_path do %>
          <%= icon("fas", "user", class: "user-icon") %>
          <h4 class="user-footer-link">ユーザー一覧</h4>
        <% end %>
      </li>
    <% else %>
      <%= render "layouts/admin_footer" %>
    <% end %>
    <li class="flex_item">
      <%= link_to logout_path, method: :delete, data: {confirm: "ログアウトしますか？"} do %>
        <%= icon("fas", "sign-out-alt", class: "logout-icon") %>
        <h4>ログアウト</h4>
      <% end %>
    </li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to image_tag('logo.png'), root_path, class: "logo" %>
  <ul>
    <li><%= link_to "ログイン", login_path %></li>
    <li><%= link_to "新規登録", signup_path %></li>
  </ul>
</header>

app/views/layouts/_login_header.html.erb
<div class="bar"></div>
<div class="logo_center">
  <div class="top_logo">
    <%= link_to image_tag('logo.png'), root_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/484e6509e8.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= render "layouts/login_header" %>
    <% end %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %> flash"><%= message %></div>
    <% end %>
    <%= yield %>
    <% if logged_in? %>
      <%= render "layouts/footer" %>
    <% end %>
  </body>
</html>